# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



[[main]]
  name = "מאמרים"
  url = "/post"
  weight = 10

[[main]]
  name = "מילון מושגים"
  url = "/dictionary"
  weight = 20

[[main_right]]
  name = "אני רוצה לעזור"
  url = "/contributing/"
  weight = 5

[[main_right]]
  name = " "
  pre = '<i class="fas fa-rss  fa-fw" ></i>'
  post= ""
  url = "http://feeds.feedburner.com/photo-nation/rss"
  weight = 10

[[main_right]]
  name = ""
  pre = """
  </a>
  <div class="nav-link">
  <form style="padding:0px 3px 0px 3px;display:inline" action="https://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('https://feedburner.google.com/fb/a/mailverify?uri=photo-nation/rss', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">
    <input type="text" style="width:200px" name="email" placeholder="לעדכונים באימייל"/>
    <input type="hidden" value="photo-nation/rss" name="uri"/>
    <input type="hidden" name="loc" value="en_US"/>
    <button type="submit" />
      <span data-toggle="tooltip" data-html="true" data-animation="true" title="השירות מופעל ע&quot;י FeedBurner מבית גוגל, כתובת האימייל אינה מגיעה לידי פוטוניישן ולא יעשה בה שימוש למעט לצורך שליחת העדכונים. ניתן לצאת מהרשימה בכל שלב.">
      הרשמה 
      <i class="far fa-question-circle text-dark" style="font-size: 0.8em; position: relative; top:-5px"></i>
      </span>
    </button>

  </form>
  </div>
  """
  post= "<a>"
  url = "hide"
  weight = 20

# [[main_right]]
#   name = ""
#   pre = '<span class="fa-stack fa-2x mr-1" style="font-size: 0.9em;"><i class="fas fa-circle fa-stack-2x" ></i><i class="fab fa-instagram fa-stack-1x fa-fw text-light" ></i>'
#   post= "</span>"
#   url = "https://instagram.com/erankutner"
#   weight = 10

# [[main_right]]
#   name = " "
#   pre = '<span class="fa-stack fa-2x mr-1" style="font-size: 0.9em;"><i class="fas fa-circle fa-stack-2x" ></i><i class="fab fa-twitter fa-stack-1x fa-fw text-light" ></i>'
#   post= "</span>"
#   url = "https://twitter.com/ekutner"
#   weight = 20

# [[main_right]]
#   name = "   "
#   pre = '<span class="fa-stack fa-2x mr-1" style="font-size: 0.9em;"><i class="fas fa-circle fa-stack-2x" ></i><i class="fab fa-facebook fa-stack-1x fa-fw text-light" ></i>'
#   post= "</span>"
#   url = "https://facebook.com/ekutner"
#   weight = 30

#   [[main_right]]
#   name = "    "
#   pre = '<span class="fa-stack fa-2x mr-1" style="font-size: 0.9em;"><i class="fas fa-circle fa-stack-2x" ></i><i class="fas fa-camera fa-stack-1x fa-fw text-light" ></i>'
#   post= "</span>"
#   url = "https://photos.kutner.org/"
#   weight = 40


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
